services:
  - type: web
    name: blockevent-backend
    env: python
    runtime: python-3.12.7
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BLOCKCHAIN_NETWORK
        sync: false
      - key: BLOCKCHAIN_RPC_URL
        sync: false
      - key: INFURA_PROJECT_ID
        sync: false
      - key: BLOCKCHAIN_PRIVATE_KEY
        sync: false
      - key: EVENTCONTRACT_ADDRESS
        sync: false
      - key: PAYMENTPROCESSOR_ADDRESS
        sync: false
      - key: TICKETNFT_ADDRESS
        sync: false
    healthCheckPath: /health
    plan: free